# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8370cf7526fa6ec983e537b5cf49109c1e8b4b05a5406064c818c7c5fd01e9da2db4d4ebe0b16adc169d9f86ac372533710d33748c9e601d34eb1a9a3b9025aa

test:
  secret_key_base: b14e96698453a5d20b44b7f2552726767266b7f3a2bcf919ea9e988e54ed376f1e022eb5926d82c2ad4d802e238b0672e90983b3089ff70ec245a4bca161f335

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
